Resources:
  AppBucketOriginAccess:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
          Description: The origin access for S3 bucket resources.
          Name: AppBucketOriginAccess
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

  AppBucketBucketCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - etergum.com
        Origins:
          - DomainName: ${self:custom.config.default.app_bucket_name}.s3.amazonaws.com
            Id: AppBucketBucketCloudFrontDistribution
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId:
              Fn::GetAtt:
                - AppBucketOriginAccess
                - Id
        Enabled: "true"
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: AppBucketBucketCloudFrontDistribution
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt IndexCludFrontFunction.FunctionMetadata.FunctionARN
        ViewerCertificate:
          AcmCertificateArn:
            Ref: StengthAndPassionCertificate
          SslSupportMethod: sni-only