Resources:
  IndexCludFrontFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: IndexCludFrontFunction
      AutoPublish: true
      FunctionCode: !Sub |
        function handler(event) {
            var request = event.request;
            var uri = request.uri;
            
            // Check whether the URI is missing a file name.
            if (uri.endsWith('/')) {
                request.uri += 'index.html';
            } 
            // Check whether the URI is missing a file extension.
            else if (!uri.includes('.')) {
                request.uri += '/index.html';
            }

            return request;
        }
      FunctionConfig:
        Comment: !Sub Append index.html to folder paths
        Runtime: cloudfront-js-1.0
        
  AppBucketOriginAccess:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
          Description: The origin access for S3 bucket resources.
          Name: AppBucketOriginAccess
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

  AppBucketBucketCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - etergum.com
        Origins:
          - DomainName: ${self:custom.config.default.app_bucket_name}.s3.amazonaws.com
            Id: AppBucketBucketCloudFrontDistribution
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId:
              Fn::GetAtt:
                - AppBucketOriginAccess
                - Id
        Enabled: "true"
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: AppBucketBucketCloudFrontDistribution
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt IndexCludFrontFunction.FunctionMetadata.FunctionARN
        ViewerCertificate:
          AcmCertificateArn:
            Ref: EtergumCertificate
          SslSupportMethod: sni-only