Resources:
  CognitoClientCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /serverless/authorizer/client/credentials
      Description: Provides the secret key for cognito user pool
      GenerateSecretString:
        PasswordLength: 60
        ExcludeCharacters: '+%;"@/\'
        IncludeSpace: false
      Tags:
      - Key: Name
        Value: /serverless/authorizer/client/credentials
      - Key: managed-by
        Value: serverless