name: serverless-authorizer

on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: deploy-services
    runs-on: ubuntu-latest
    steps:
      - name: Action checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Build API dependencies
        run: |
          cd $GITHUB_WORKSPACE/functions/user-api/src
          mkdir fastapi-authorizer && cd fastapi-authorizer
          pip3 install -r ../requirements.txt -t python/lib/python3.9/site-packages

      - name: Build FastAPI layer
        run: |
          cd $GITHUB_WORKSPACE/functions/user-api/src/fastapi-authorizer
          zip -r $GITHUB_WORKSPACE/fastapi-authorizer-layer-artifact.zip *

      - name: Build API
        run: |
          cd $GITHUB_WORKSPACE/functions/user-api/src
          rm requirements.txt
          rm -r fastapi-authorizer
          zip -r $GITHUB_WORKSPACE/api-artifact.zip *
      
      - name: Serverless deployment
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
